version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  target-branch: develop
- package-ecosystem: npm
  directory: "/packages/core/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  target-branch: develop
- package-ecosystem: npm
  directory: "/packages/ui/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  target-branch: develop