version: '3'
services:
  app:
    container_name: polygloat_js_e2e
    image: polygloat/polygloat:latest
    ports:
      - 8202:8080
      - 8092:8091
    environment:
      - polygloat.internal.populate=true
      - polygloat.internal.controllerEnabled=true
      - "polygloat.screenshots-url=http://localhost:8202/screenshots"
      - polygloat.authentication.needs-email-verification=true
      - polygloat.authentication.registrations-allowed=true
      - polygloat.internal.fake-emails-sent=true
      - polygloat.authentication.initialPassword=admin
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8091,server=y,suspend=n
  e2e:
    container_name: polygloat_js_e2e_serve_testapps_core
    build: ../docker
    volumes:
      - "../testapps/core:/data"
    ports:
      - 8101:8101
    command: ["npm", "run", "serve"]
    working_dir: /data