name: Prerelease

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Npm install lerna
        run: npm install -g lerna

      - name: Build (build & test)
        run: ./gradlew build

      - name: Set git globals
        run: |
          git config --local user.email "machine@polygloat.io"
          git config --local user.name "Polygloat Machine"

      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create lerna version
        run: lerna version prerelease --yes

      - name: Rebuild ngx package with correct version and without Ivy
        run: ./gradlew buildNgxForPublish

      - name: Publish
        run: lerna publish from-git --yes

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress
          path: |
            cypress/videos/**/*
            cypress/screenshots/**/*