name: Test

on:
  push:
    brancges:
      "!prerelease-*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Npm install
        run: npm install

      - name: Unit test
        run: npm run test

      - name: Build core
        run: npm run build

      - name: Build testApps
        run: npm run buildTestApps

      - name: Start docker stack
        run: docker-compose -f test-docker-compose.yml up -d

      - name: Wait for running container
        run: 'until docker logs --since 5m polygloat | grep -m 1 "started on port(s): 8080"; do : ;done'

      - name: Run cypress test
        run: "npm run cy:run"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress
          path: |
            cypress/videos/**/*
            cypress/screenshots/**/*